{

    "token": 'oIW2kTqfttf8ImZNxiwixVI37IJ7wcb4LlaYolHkI12FFOz2_aArHbotm2BeMVThtw4k20IJlmVDx0znQzdzVy3XysNhDiRy7AAwrTtFVzVLXtRPeutk2OZ-',
    "study_id": '6659f3c7a48352a6c226877f',
    "max_concurrent_sessions": 5,
    "workload_checker_period": 300
}
