{

    "token": 'oIW2kTqfttf8ImZNxiwixVI37IJ7wcb4LlaYolHkI12FFOz2_aArHbotm2BeMVThtw4k20IJlmVDx0znQzdzVy3XysNhDiRy7AAwrTtFVzVLXtRPeutk2OZ-',
    "study_id": '665c7a6928867ff5c68b6e92',
    "max_concurrent_sessions": 2,
    "workload_checker_period": 300
}
