{

    "token": 'JqssTDopzDg3WBd92PwEKwypDRIYTFVwW6yfXnOgmxTyTOQ8WFrxhGQi1g-ViL9V6s9428GFPuTxDxLNKtK_BFxFXgbw_hOAo05U4B_ADA7yb6b7ZEqCajuB',
    "study_id": '6657597425deaaf7f9db9c01',
    "max_concurrent_sessions": 30,
    "workload_checker_period": 300
}
