{

    "token": 'oIW2kTqfttf8ImZNxiwixVI37IJ7wcb4LlaYolHkI12FFOz2_aArHbotm2BeMVThtw4k20IJlmVDx0znQzdzVy3XysNhDiRy7AAwrTtFVzVLXtRPeutk2OZ-',
    "study_id": '6659f3e1d8cd7577c303a6ac',
    "max_concurrent_sessions": 1,
    "workload_checker_period": 300
}
