{

    "token": 'JqssTDopzDg3WBd92PwEKwypDRIYTFVwW6yfXnOgmxTyTOQ8WFrxhGQi1g-ViL9V6s9428GFPuTxDxLNKtK_BFxFXgbw_hOAo05U4B_ADA7yb6b7ZEqCajuB',
    "study_id": '6659f3e1d8cd7577c303a6ac',
    "max_concurrent_sessions": 1,
    "workload_checker_period": 300
}
