{

    "token": 'JqssTDopzDg3WBd92PwEKwypDRIYTFVwW6yfXnOgmxTyTOQ8WFrxhGQi1g-ViL9V6s9428GFPuTxDxLNKtK_BFxFXgbw_hOAo05U4B_ADA7yb6b7ZEqCajuB',
    "study_id": '66545ef9b5999bd051e72f04',

    "max_concurrent_sessions": 30,
    "workload_checker_period": 300
}
