{
    "port": 8880,

    "server_name": "potato annotator",

    "annotation_task_name": "Traumatic Event Detection",
    
    # "prolific": {
    # "config_file_path": 'configs/prolific_config.yaml'
    # },


    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv",

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
#     "annotation_codebook_url": "https://docs.google.com/document/d/16ZV4P9lwR8lWbfXLOwvcw7xV4QVGtHXygw1lzo-A3jY/edit?usp=sharing",

    "surveyflow": {
      "on": True,
    
     "order": [
            "pre_annotation",
            "post_annotation"
        ],

      "pre_annotation": [
        # {'file':'surveyflow/instruction.jsonl','text':'Overview of the task'}
        {'file':'surveyflow/instruction copy.jsonl','text':'Overview'}],
  
      "post_annotation": [ 


      #{'file':'surveyflow/post_annotation_question.jsonl','text':"Thank you for your valuable contributions to our study! Our goal is to understand how doctors can communicate better with patients by looking at different perceptions of the doctors’ qualities. Understanding your personal experiences with the medical system will help us to contextualize your responses. We invite you to share insights by answering the following questions. Your answers to these questions are strictly confidential and anonymous."}, 
       {'file':'surveyflow/end_fin.jsonl','text':'End of survey'}
      
      ],
    },


    "data_files": [
    
       "data/pilot_data.json"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        # "context_key": "context"
    },


   
    "automatic_assignment": {
      #whether do automatic task assignment for annotators, default False.
      "on": True,
      "output_filename": 'task_assignment_2.json',
      "sampling_strategy": 'random',

      "labels_per_instance": 3,
      # "instance_per_annotator": 1,
      "instance_per_annotator": 30,
      "test_question_per_annotator": 0, # you must set up the test question in surveyflow to use this function

      "users": [  ],
    },


    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },

    "login": {
        "type": "url_direct",
        "url_argument": "PROLIFIC_PID"
    },

    #the jumping-to-id function will be disabled if "jumping_to_id_disabled" is True
    "jumping_to_id_disabled": False,

    #the navigation bar will be hidden to the annotators if "hide_navbar" is True
    "hide_navbar": True,

    #list_as_text is used when the input text is actually a list of texts, usually used for best-worst-scaling or dialogue analysis
    "list_as_text": {
      "text_list_prefix_type": 'none', #whether automatically insert a prefix for each line, currently supporting 'number', 'alphabet', 'number'
      "horizontal": True,
    },

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,

    "annotation_schemes": [

        {
            "annotation_type": "radio",
            #"arrangement": "vertical",
            "name": "select_trauma",
            "description": "Does this text contain a traumatic event? 
            Traumatic events are defined as \"exposure to actual or threatened death, serious injury, sexual violence, or severe mental abuse,\" whether directly encountered or witnessed. It also counts as a traumatic event if something like that has happened to a close family member or friend.",
            "labels": ["yes", "no", "uncertain"],
            # If true, numbers [1-len(labels)] will be bound to each label. Aannotations with more than 10 are not supported with this simple keybinding and will need to use the full item specification to bind all labels to keys.
            "sequential_key_binding": True,                        
        },       
    ],
    # if you want to use your own template,
    # please replace the string as a path to the template
    # "base_html_template": "../../potato/templates/Doctor-Patient-Conversation-Analysis-base_template.html",
    # "base_html_template": "../templates/Dialogue-Analysis-Dialogue-Analysis-base_template copy.html",
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default",

}