{

    "token": 'oIW2kTqfttf8ImZNxiwixVI37IJ7wcb4LlaYolHkI12FFOz2_aArHbotm2BeMVThtw4k20IJlmVDx0znQzdzVy3XysNhDiRy7AAwrTtFVzVLXtRPeutk2OZ-',
    "study_id": '665ce2da944e5ac6a2f5329c',
    "max_concurrent_sessions": 3,
    "workload_checker_period": 300
}
