{
    "token": 'oIW2kTqfttf8ImZNxiwixVI37IJ7wcb4LlaYolHkI12FFOz2_aArHbotm2BeMVThtw4k20IJlmVDx0znQzdzVy3XysNhDiRy7AAwrTtFVzVLXtRPeutk2OZ-',
    "study_id": '666360914f5198986065dd5c',
    "max_concurrent_sessions": 30,
    "workload_checker_period": 300
}
